add a dependancy on sq scan

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -53,7 +53,7 @@ jobs:
           # Disabling shallow clones is recommended for improving the relevancy of analysis
           fetch-depth: 0
 
-      - name: SonarQube Scan
+      - name: sonarqube_scan
         uses: sonarsource/sonarqube-scan-action@master
         env:
           SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
@@ -64,8 +64,25 @@ jobs:
             -Dsonar.sources=./src
             -Dsonar.organization=lapayne
 
+
+      # Check the Quality Gate status.
+      - name: SonarQube Quality Gate check
+        id: quality-gate
+        uses: sonarsource/sonarqube-quality-gate-action@master
+        with:
+          pollingTimeoutSec: 600
+        env:
+          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
+    
+      # New Step: Fail the build if the quality gate is not 'OK'
+      - name: Fail build on quality gate failure
+        if: ${{ steps.quality-gate.outputs.qualityGateStatus != 'OK' }}
+        run: |
+          echo "The SonarQube quality gate failed."
+          exit 1
+
   build_and_push_docker:
-    needs: unit_test
+    needs: [unit_test, sonarqube_scan]
     runs-on: ubuntu-latest
     permissions:
       contents: read
